### ISSUE TITLE
Pickup dates are in September 2020 and we are in October

### ISSUE THREAD

**Issue by Dave-Bryant** [simonhq/act_garbage#1]

**Comment by simonhq** [comment]
Hi David,

I noticed this myself and I have put in a request to the dataset owner on the act.data.gov.au website where I am getting the data for this.

https://www.data.act.gov.au/Community-Services/ACT-Suburb-Next-Garbage-Recycling-and-Green-Waste-/jzzy-44un

If they don't get back to me in the next week I will see if I can source the information from somewhere else.

Simon.

**Comment by Dave-Bryant** [comment]
Thx Simon, It is a great app.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by simonhq** [comment]
Seems to be working again.
