### ISSUE TITLE
Act govt dataset incorrect 

### ISSUE THREAD

**Issue by Dave-Bryant** [simonhq/act_garbage#2]
Simon, the 2021 dataset first match the published schedule here. [Here](https://www.cityservices.act.gov.au/__data/assets/pdf_file/0003/1678341/2021-bin-collection-North-A-calendar.pdf) eg I am in Nicholls and the ACT dataset says my recycling is in 2 weeks but it is next week. I am happy to contact them as this isn’t your issue.

**Comment by Dave-Bryant** [comment]
Simon my post should read ‘the 2021 dataset does not match the published schedule’

**Comment by Dave-Bryant** [comment]
Simon, they have fixed the dataset.

**Comment by simonhq** [comment]
Hey Dave,

Thanks for following it up, sorry I didn't see this sooner, but yes I would just be emailing them to ask what was going on.

Assuming you are in Canberra :) , so if you want to catch up sometime to chat about home automation stuff over a coffee etc. let me know.

Simon.

**Comment by Dave-Bryant** [comment]
Simon,
That would be great. I am in Gunghalin.  I am free most mornings next week. You suggest a time and place.

David Bryant
________________________________

**Comment by simonhq** [comment]
I am in Tuggeranong, but will be in the city on Tuesday for work, do you know anywhere good near Garema place? I am not really a coffee drinker, so I don't spend much time working out which place is the best. I should be able to make any time at this point.
